server:
  port: 8087

spring:
  application:
    name: Maze-Agent-qwerty


  thymeleaf:
      cache: false

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
